# This workflow will run Cypress automation tests on every push to the main/dev branch

name: E-commerce Web App Tests

on:
  push:
    branches: [main, dev]
  

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Set up Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run